### ISSUE TITLE
Реализация rates-service

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/rates-service#1]
- [x] Сбор информации об актуальном курсе из внешнего источника (coinmarketcap)
- [x] Хранение (исторических) данных о курсе 

Реализовать запросы для 

- [x] получения исторических данных курса
- [x] получения актуальных данных курса
- [x] Реализовать взаимодействие по jsonrpc c другими сервисами

Список пар
GOLOS/USD, GOLOS/EUR, GOLOS/RUB
GBG/USD, GBG/EUR, GBG/RUB

**Comment by bacher** [comment]
Одно но, пока что не готовы запросы за данными из браузера.
